spring:
  application:
    name:
      security-service:

  datasource:
    url:
      jdbc:postgresql://localhost:5432/user_db
    hikari:
      username: postgres
      password: garage123
      driver-class-name: org.postgresql.Driver
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


token:
  signing:
    key:
      53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A753278551